src/components/core/cards/nft-card/nft-card.tsx
src/components/nft-metadata/nft-metadata.tsx

[Description](https://www.notion.so/Post-Release-Feedback-4da676e97710421c8a19781d09f6dc93#81aede970aa14d44a7388bfe455e690a)
- Added # before token ids across app
- [Notion](https://www.notion.so/Post-Release-Feedback-4da676e97710421c8a19781d09f6dc93#81aede970aa14d44a7388bfe455e690a)

refactor: 💡 added # symbol to token IDs across the app

---

src/components/icons/index.ts
src/components/plug/plug-button.tsx

- [Description](https://www.notion.so/Post-Release-Feedback-4da676e97710421c8a19781d09f6dc93#5b5b6a65e0ab401f8ce021ed5623c1a8)
- Moved `myNfts` to plug dropdown menu
- [Notion](https://www.notion.so/Post-Release-Feedback-4da676e97710421c8a19781d09f6dc93#5b5b6a65e0ab401f8ce021ed5623c1a8)
https://user-images.githubusercontent.com/51888121/176232315-ea8089d3-5e47-4dd5-86bb-2e02bf60e3ed.mov

refactor: 💡 added my nfts to plug dropdown

---

src/integrations/kyasshu/kyasshu-urls.ts
src/store/features/marketplace/async-thunks/accept-offer.ts
src/store/features/marketplace/async-thunks/cancel-listing.ts
src/store/features/marketplace/async-thunks/cancel-offer.ts
src/store/features/marketplace/async-thunks/direct-buy.ts
src/store/features/marketplace/async-thunks/make-listing.ts
src/store/features/marketplace/async-thunks/make-offer.ts

Use the Kyasshu jelly marketplace sync, instead of cap sync.
⚠️ Relates and depends on https://github.com/Psychedelic/kyasshu/pull/47 once merged, this PR should point to latest of Kyasshu feat/marketplace
https://user-images.githubusercontent.com/236752/178545841-d58d0da1-c27b-4b59-9f67-bc7a2c415376.mp4
Left bottom window shows the status of the request made in the top right window `capJellySync`:

chore: 🤖 kyasshu sync via jelly mkp sync

---

src/locales/en/translation.json

update Recently Actioned sort name to Recent Actions
- [Discord](https://discord.com/channels/837010835423494144/911179346604089374/996056501389099039)

refactor: 💡update Recently Actioned sort name to Recent Actions

---

src/components/core/cards/nft-card/nft-card.tsx
src/components/core/cards/nft-card/styles.ts
src/components/core/infinite-list/styles.ts
src/components/core/infinite-list/virtualized-grid.tsx
src/components/items/collection-items.tsx

Modified NFT Listing.
- [Notion](https://www.notion.so/Nice-to-have-Mobile-responsiveness-7e7a516084ec41d9989b596d8111e83d)
https://user-images.githubusercontent.com/51888121/179122317-90922957-40c2-4126-ac1c-d8fb0b041f39.mov

refactor: 💡 responsive nfts listing modification

---

src/components/core/accordions/about-accordion.tsx
src/components/core/accordions/offer-accordion.tsx
src/components/core/accordions/styles.ts
src/components/core/buttons/styles.ts
src/components/core/chips/styles.ts
src/components/core/table-cells/mobile-item-details.tsx
src/components/core/table-cells/styles.ts
src/components/core/table-cells/type-details-cell.tsx
src/components/items/collection-items.tsx
src/components/modals/buy-now-modal.tsx
src/components/modals/cancel-listing-modal.tsx
src/components/modals/change-price-modal.tsx
src/components/modals/make-offer-modal.tsx
src/components/modals/styles.ts
src/components/nft-action-bar/index.ts
src/components/nft-action-bar/nft-action-bar.tsx
src/components/nft-action-bar/nft-action-buttons.tsx
src/components/nft-action-bar/styles.ts
src/components/nft-details/nft-details.tsx
src/components/nft-details/styles.ts
src/components/nft-metadata/nft-metadata.tsx
src/components/nft-metadata/styles.ts
src/components/tables/activity-table.tsx
src/components/tables/nft-activity-table.tsx
src/components/tables/nft-offers-table.tsx
src/components/tables/styles.ts
src/locales/en/translation.json
src/views/NFTView/styles.ts

Mobile Responsive Details Screen.
- [Notion](https://www.notion.so/Nice-to-have-Mobile-responsiveness-7e7a516084ec41d9989b596d8111e83d)
https://user-images.githubusercontent.com/51888121/179668036-27a105f2-6033-4273-bd2c-c38d76ea108b.mov
https://user-images.githubusercontent.com/51888121/179668629-5dc24f4e-f28f-401d-adfb-9138adf526b2.mov

feat: 🎸 mobile responsive nft details page

---

src/components/core/skeleton/styles.ts
src/components/core/table-cells/mobile-item-details.tsx
src/components/core/table-cells/price-details-cell.tsx
src/components/core/table-cells/styles.ts
src/components/core/table-cells/text-cell.tsx
src/components/modals/accept-offer-modal.tsx
src/components/modals/cancel-offer-modal.tsx
src/components/modals/styles.ts
src/components/tables/my-offers-table.tsx
src/components/tables/styles.ts
src/components/tables/table-layout.tsx
src/components/tables/table-skeletons.tsx
src/components/tables/user-activity-table.tsx
src/components/tabs/mobile-my-offers-tab.tsx
src/locales/en/translation.json
src/views/OffersView/index.tsx
src/views/OffersView/styles.ts
src/views/UserActivityView/styles.ts

Mobile Responsive Tables
https://user-images.githubusercontent.com/51888121/179875559-72ae244c-5089-4eca-afc0-73d71592e698.mov
https://user-images.githubusercontent.com/51888121/179875543-6e2daa85-ad53-4eab-8a03-b285aa9e1ea9.mov

feat: 🎸 responsive mobile tables

---

src/components/core/table-cells/mobile-item-details.tsx
src/components/core/table-cells/styles.ts

styles: 💅🏼 removed unused code

---

src/components/core/table-cells/type-details-cell.tsx
src/components/tables/nft-activity-table.tsx
src/constants/operations.ts
src/locales/en/translation.json
src/utils/parser.ts

The activity table is missing the mint event type and related handling for this type.

fix: 🐛 token activity table

---

src/utils/parser.ts

Filter out events which are not user-friendly.
⚠️ Depends on https://github.com/Psychedelic/nft-marketplace-fe/pull/463

chore: 🤖 filter irrelevant cap events for activity table

---

src/components/core/table-cells/type-details-cell.tsx
src/constants/operations.ts
src/locales/en/translation.json
src/utils/nfts.ts
src/utils/parser.ts

The transfer event should be displayed and handled correctly.

chore: 🤖 show and handle transfer event

---

src/components/core/table-cells/type-details-cell.tsx
src/components/tables/nft-activity-table.tsx
src/config/env.ts
src/constants/operations.ts
src/integrations/kyasshu/kyasshu-urls.ts
src/locales/en/translation.json
src/utils/nfts.ts
src/utils/parser.ts

chore: 🤖 switch to kyasshu production

---

src/config/env.ts

chore: 🤖 test env, crowns collection canister id

---

src/components/nft-details/nft-details.tsx

Displaying traits on desktop screen

fix: 🐛 displaying traits on desktop screen

---

src/config/env.ts

Should fix the WICP Test canister id in the config env vars.

fix: 🐛 wicp test canister id

---

src/components/modals/buy-now-modal.tsx
src/components/modals/make-offer-modal.tsx
src/components/nft-details/nft-details.tsx
src/store/features/plug/plug-slice.ts
src/utils/balance.ts

Display insufficient balance modal

fix: 🐛 display insufficient balance modal

---

src/components/core/accordions/checkbox-filter-accordion.tsx
src/components/core/checkbox/checkbox.tsx
src/components/nft-details/nft-details.tsx
src/store/features/filters/async-thunks/get-filter-traits.ts
src/store/features/nfts/async-thunks/get-nft-details.ts
src/store/features/nfts/async-thunks/get-nfts.ts

Decouple traits to allow it to be used in more use cases
https://user-images.githubusercontent.com/51888121/183316272-dbf079f1-4be0-4693-805d-c054cd9a3ce6.mov

refactor: 💡 decoupled traits

---

src/components/core/accordions/about-accordion.tsx
src/components/core/table-cells/item-details-cell.tsx
src/components/filters/filters.tsx
src/components/modals/buy-now-modal.tsx
src/components/modals/cancel-listing-modal.tsx
src/components/modals/change-price-modal.tsx
src/components/modals/make-offer-modal.tsx
src/components/modals/sell-modal.tsx
src/components/nft-details/nft-details.tsx
src/components/nft-list/nft-list.tsx
src/components/tables/nft-activity-table.tsx
src/components/tabs/collection-tabs.tsx
src/integrations/kyasshu/index.ts
src/integrations/kyasshu/kyasshu-urls.ts
src/store/features/filters/async-thunks/get-filter-traits.ts
src/store/features/marketplace/async-thunks/cancel-listing.ts
src/store/features/marketplace/async-thunks/direct-buy.ts
src/store/features/marketplace/async-thunks/get-token-listing.ts
src/store/features/marketplace/async-thunks/make-listing.ts
src/store/features/marketplace/async-thunks/make-offer.ts
src/store/features/marketplace/marketplace-slice.ts
src/store/features/nfts/async-thunks/get-collection-data.ts
src/store/features/nfts/async-thunks/get-nft-details.ts
src/store/features/nfts/async-thunks/get-nfts.ts
src/store/features/tables/async-thunks/get-token-metadata.ts
src/store/features/tables/async-thunks/get-token-transactions.ts

Update collection Id's with dynamic value

refactor: 💡 update collection Id's with dynamic value

---

src/components/icons/index.ts
src/components/modals/approve-xtc.tsx
src/components/modals/styles.ts
src/components/onboarding/collection-details.tsx
src/components/onboarding/connect-canister-id.tsx
src/components/onboarding/nft-details.tsx
src/components/onboarding/onboarding-ui.tsx
src/components/onboarding/styles.ts
src/components/traits/index.ts
src/components/traits/styles.ts
src/components/traits/traits.tsx
src/constants/approve-xtc.ts
src/locales/en/translation.json
src/store/features/onboarding/onboarding-slice.ts

Onboarding ui development
- Added new progress bars to previous work done
- Began work on the traits and properties
- Refactored error handling and some styles
- [GH Projects](https://github.com/orgs/Psychedelic/projects/6/views/11)
https://user-images.githubusercontent.com/51888121/187111577-a6ee1af2-1412-4ab4-9f13-458284d2399a.mov

refactor: 💡 new onboarding ui updates

---

src/components/icons/index.ts
src/components/modals/edit-traits-modal.tsx
src/components/modals/index.ts
src/components/modals/styles.ts
src/components/onboarding/nft-details.tsx
src/components/onboarding/styles.ts
src/components/tabs/edit-traits-tab.tsx
src/components/tabs/index.ts
src/components/tabs/styles.ts
src/components/traits/styles.ts
src/components/traits/traits.tsx
src/locales/en/translation.json
src/stitches.config.ts

Onboarding properties and traits section
- [GH Projects](https://github.com/orgs/Psychedelic/projects/6/views/11)
https://user-images.githubusercontent.com/51888121/187318790-db0d30e5-5984-4b7b-b1d0-e02c0ca2229e.mov

feat: 🎸 set up onboarding properties/traits

---

src/components/plug/plug.tsx
src/integrations/plug/plug.utils.ts

Update plug connection whitelisting
https://user-images.githubusercontent.com/40259256/188112199-fe28f37b-5d2a-46ef-9065-f06286bfe9b3.mov

refactor: 💡 plug connection whitelisting

---

package.json
yarn.lock

Should use latest of jelly js and related jelly service.

chore: 🤖 use latest of jelly-js

---

src/components/nft-details/nft-details.tsx
src/store/features/marketplace/async-thunks/cancel-listing.ts
src/store/features/marketplace/async-thunks/get-token-listing.ts
src/store/features/nfts/async-thunks/get-nft-details.ts

Cancel modal, should trigger the v2 cancel listing.

chore: 🤖 cancel listing handling

---

src/components/core/dropdown/price-filter-dropdown.tsx
src/components/nft-list/nft-list.tsx
src/integrations/kyasshu/index.ts
src/locales/en/translation.json
src/store/features/filters/filter-slice.ts
src/store/features/nfts/async-thunks/get-all-nfts.ts
src/store/features/nfts/nfts-slice.ts
src/utils/sorting.ts

Refactored sorting to use the jelly-js library and the v2 backend.
- [GH Project](https://github.com/orgs/Psychedelic/projects/6/views/11)
https://user-images.githubusercontent.com/51888121/189157256-4b955846-c1f5-484b-aa55-97b15fb18e23.mov

feat: 🎸 sorting for nft list

---

src/components/core/accordions/offer-accordion.tsx
src/components/modals/cancel-offer-modal.tsx
src/store/features/marketplace/async-thunks/cancel-offer.ts
src/store/features/marketplace/async-thunks/make-offer.ts

Update cancel offer integration using jelly js
- [issue-504](https://github.com/Psychedelic/nft-marketplace-fe/issues/504)
https://user-images.githubusercontent.com/40259256/189603808-fdb80801-4a29-4fb2-9808-2fca58bd2449.mov

feat: 🎸 cancel offer integration using jelly js

---

.scripts/generate-mocked-tokens-v2.sh

The mock generator should use batch insert.
⚠️ Related to https://github.com/Psychedelic/crowns/pull/55

perf:⚡️ mock token generator use batch insert

---

src/locales/en/translation.json
src/store/features/nfts/async-thunks/get-all-nfts.ts

The name should be consistent, as such should be picked from dip721 name.
⚠️ Requires https://github.com/Psychedelic/nft-marketplace-fe/pull/528
- https://github.com/Psychedelic/nft-marketplace-fe/issues/531

fix: 🐛 collection naming

---

package.json
src/components/core/accordions/checkbox-filter-accordion.tsx
src/components/core/checkbox/checkbox.tsx
src/components/core/checkbox/styles.ts
src/components/core/chips/filtered-traits-chip.tsx
src/components/core/empty-states/empty-state.tsx
src/components/filters/filters.tsx
src/components/items/collection-items.tsx
src/components/nft-list/nft-list.tsx
src/integrations/kyasshu/index.ts
src/integrations/kyasshu/utils.ts
src/store/features/filters/async-thunks/get-filter-traits.ts
src/store/features/nfts/async-thunks/get-all-nfts.ts

Fetching and displaying the list of traits from jelly-js.
- [GH Project](https://github.com/orgs/Psychedelic/projects/6/views/11)
https://user-images.githubusercontent.com/51888121/189559532-57f1a056-4ee9-4bdc-b72f-0baac70d3a5d.mov
https://user-images.githubusercontent.com/51888121/189750195-e69fc95b-8236-4e25-ae34-d841f11fd825.mov

feat: 🎸 integration traits with jelly-js

---

src/store/features/nfts/async-thunks/get-nft-details.ts

Use generic actor for dip 721 contract

chore: 🤖 use generic actor dip 721

---

src/components/tables/activity-table.tsx
src/components/tables/user-activity-table.tsx
src/store/features/cap/async-thunks/get-token-contract-root-bucket.ts
src/store/features/filters/async-thunks/get-filter-traits.ts
src/store/features/tables/async-thunks/get-cap-activity.ts
src/store/features/tables/async-thunks/get-user-activity.ts

The contract ids are of collection and not the marketplace
⚠️ Requires https://github.com/Psychedelic/nft-marketplace-fe/pull/533
- https://github.com/Psychedelic/nft-marketplace-fe/issues/532

fix: 🐛 contract root bucket for jelly v2

---

src/declarations/marketplace-v2.d.ts
src/declarations/marketplace-v2.did.ts

Update IDL for latest Marketplace v2, which has token responses

chore: 🤖 update idl for latest marketplace v2 token response

---

src/components/modals/accept-offer-modal.tsx
src/store/features/marketplace/async-thunks/accept-offer.ts

Accept offer using jelly js
- [Issue 540](https://github.com/Psychedelic/nft-marketplace-fe/issues/540)

feat: 🎸 accept offer using jelly js

---

src/components/nft-details/nft-details.tsx

Handle undefined traits on details screen

fix: 🐛 handled undefined traits on details screen

---

package.json
src/components/filters/filters.tsx
src/components/items/collection-items.tsx
src/components/nft-list/nft-list.tsx
src/index.tsx
src/integrations/jelly-js/jelly-js.utils.ts
src/integrations/kyasshu/index.ts
src/store/features/filters/async-thunks/get-filter-traits.ts
src/store/features/marketplace/async-thunks/get-nft-offers.ts
src/store/features/marketplace/async-thunks/get-token-listing.ts
src/store/features/marketplace/marketplace-slice.ts
src/store/features/nfts/async-thunks/get-all-nfts.ts
src/store/features/nfts/async-thunks/get-my-nfts.ts
src/store/features/nfts/async-thunks/index.ts
src/store/features/nfts/nfts-slice.ts
src/utils/jelly.ts
yarn.lock

Migration of My NFTs to jelly v2. Also took the opportunity to better type JellyJS stuff.
- Migrated My NFTs to Jelly v2
- Hid all filters when selecting My NFTs, since there are no filters for that request.
- Correctly typed JellyJS variables and fixed typing issues after that.
- Added a small fix in index.ts for an issue with BigInt
When the user doesn't have NFTs
When the user has NFTs
https://user-images.githubusercontent.com/5349650/190470287-034fb01c-2a26-4f7d-809c-8d4db5ff65de.mov

feat: 🎸 migrated My NFTs section to jelly v2

---

src/store/features/marketplace/async-thunks/get-user-offers.ts
src/utils/parser.ts

fix: 🐛 fix type bug

---

src/components/tables/my-offers-table.tsx

Fixed my offers received loading bug.
https://user-images.githubusercontent.com/51888121/191248473-e5e5b20b-3605-4d9a-809a-ea292ebe8186.mov

fix: 🐛 fixed my offers loading bug

---

package.json
src/components/nft-list/nft-list.tsx
src/components/tabs/collection-tabs.tsx
src/integrations/kyasshu/index.ts
src/store/features/nfts/async-thunks/get-all-nfts.ts
src/store/features/nfts/async-thunks/get-collection-data.ts
src/store/features/nfts/nfts-slice.ts
yarn.lock

Migrated fungibleFloor, fungibleVolume, owners and total items to v2 using JellyJS
**Note:** fugibleFloor and fungibleVolume are returning 0 at the moment in the BE
- Updated JellyJS
- Used getUniqueNFTOwners to get unique owners
- Got fungibleVolume, fungibleFloor and items from getCollections

feat: 🎸 migrated owners, floor, volume and items to v2

---

src/components/core/dropdown/price-filter-dropdown.tsx
src/components/core/empty-states/empty-state.tsx
src/components/filters/filters.tsx
src/components/items/collection-items.tsx

Set up the buy now and has offer filter behaviour with the sort dropdown.
- [GH Projects](https://github.com/Psychedelic/nft-marketplace-fe/issues/559)
https://user-images.githubusercontent.com/51888121/191395185-505e70cb-3e9c-4e1c-86db-1f354ecf5864.mov

feat: 🎸 buy now/has offers filter

---

.scripts/generate-mocked-tokens-v2.sh
src/store/features/cap/async-thunks/get-token-contract-root-bucket.ts
src/store/features/tables/async-thunks/get-cap-activity.ts
yarn.lock

Call the cap txns by the marketplace id not the collection user root bucket
⚠️ Requires https://github.com/Psychedelic/kyasshu/pull/95
⚠️ Depends on https://github.com/Psychedelic/nft-marketplace-fe/pull/565 which should be merged first

chore: 🤖 kyasshu's cap txns by the collection marketplace id

---

.scripts/clear_cache.sh
package.json

To clear the .cache directory used by mock generator

chore: 🤖 clear cache script

---

.scripts/generate-mocked-tokens-v2.sh

Should exit if JQ dependency not found!

chore: 🤖 jq command dependency verification

---

.scripts/generate-mocked-tokens-v2.sh

For some reason, the cache process causes the mock generator to fail, which is related to having the for loop iterating repeated items for some reason which should be looked separately.

chore: 🤖 revert latest mockgen changes
