- src/components/core/dropdown/price-filter-dropdown.tsx
- src/constants/sort-options.ts
- src/locales/en/translation.json
- src/store/features/filters/async-thunks/get-search-results.tsx
- src/store/features/nfts/async-thunks/get-nfts.ts
Update sorting categories by adding `High to Low & Low to High`
- [Notion ticket](https://www.notion.so/Post-Release-Feedback-4da676e97710421c8a19781d09f6dc93#82b4d045cca64a4e9b71cc8a235bc5e0)
https://user-images.githubusercontent.com/40259256/176387196-763c698d-e78c-406d-b3f1-df05dcbcb772.mov
> feat: 🎸 sort by price

- package.json
Type conversion error; https://forum.dfinity.org/t/cannot-convert-a-bigint-value-to-a-number/5470/12
> fix: 🐛 type conversion error browserlist

- .scripts/kyasshu/start.sh
Update the kyasshu start script because ic-history-router is now cap-router.
> chore: 🤖 ic-history-router is now cap-router

- .scripts/start.sh
ic history router is now cap router, as such the start script has to change
> fix: 🐛 start script cap router name

- src/components/core/accordions/offer-accordion.tsx
show top offers and make offer action buttons in NFT details page
- [Discord](https://discord.com/channels/837010835423494144/911179346604089374/996359757239689228)
- [Discord](https://discord.com/channels/837010835423494144/911179346604089374/996364306830602240)
> fix: 🐛 show top offers and make offer action buttons in NFT details page

- .scripts/kyasshu/start.sh
The Kyasshu start script should include the allowed canister ids as a json string.
> chore: 🤖 kyasshu allowed canister ids env vars

- src/locales/en/translation.json
Update insufficient balance text while making an offer
- [Notion](https://discord.com/channels/837010835423494144/911179346604089374/998646549439590510)
> refactor: 💡update insufficient balance text while making an offer

- src/components/plug/plug-button.tsx
Redirect to home page with my nfts filter applied from dropdown
- [Notion](https://discord.com/channels/837010835423494144/911179346604089374/996957913669185626)
https://user-images.githubusercontent.com/40259256/179738636-82734297-e9ff-4aca-bb6a-8b28027af4eb.mov
> fix: 🐛 redirect to home page with my nfts filter applied from dropdown

- src/components/core/cards/nft-card/nft-card.tsx
Show last sale details in NFT card when there is no offer, but sold
Issue:
Fix:
> fix: 🐛 show last sale details in NFT card when there is no offer, but sold

- src/integrations/kyasshu/kyasshu-urls.ts
Should use the correct endpoint, when prod kyasshu  is used.
⚠️ Requires Kyasshu prod to be used, at the moment we're still in kyasshu-dev
```
curl -X GET https://kyasshu.fleek.co/cap/token/txns/vlhm2-4iaaa-aaaam-qaatq-cai/9750
```
> chore: 🤖  kyasshu token endpoint update

- src/utils/parser.ts
The token identifier and value have to be parsed to take into account U64 and text containing "_" special underscore character.
> fix: 🐛 token identifier for activity table

- src/App.tsx
- src/constants/response-status.ts
- src/locales/en/translation.json
- src/store/features/filters/async-thunks/get-filter-traits.ts
- src/store/features/marketplace/async-thunks/get-token-listing.ts
- src/store/features/nfts/async-thunks/get-collection-data.ts
- src/store/features/nfts/async-thunks/get-nft-details.ts
- src/store/features/nfts/async-thunks/get-nfts.ts
- src/store/features/settings/settings-slice.ts
- src/utils/error.ts
- src/views/CollectionView/index.tsx
- src/views/CollectionView/styles.ts
- src/views/NFTView/index.tsx
- src/views/PageNotFoundView/index.tsx
- src/views/PageNotFoundView/styles.ts
Show Page not found UI when user tries to fetch unknown collection or NFT
https://user-images.githubusercontent.com/40259256/186335176-6b005e4b-d9a3-4050-8c5e-ddf322ca6cb8.mov
> feat: 🎸 Handle page not found UI for unknown Collection or NFT

- src/components/modals/buy-now-modal.tsx
- src/components/modals/make-offer-modal.tsx
Fix insufficient balance error while making offer and direct buy
Issue: 
https://user-images.githubusercontent.com/40259256/186343541-59dea9f8-5775-425c-a1a0-087bee16875e.mov
Fix:
https://user-images.githubusercontent.com/40259256/186343986-78da63b3-57ae-4442-89ff-655ed9f2f0a5.mov
> fix: 🐛 insufficient balance error while making offer and direct buy

- .scripts/start.sh
For jelly-js it's necessary to have a `REACT_APP_HUB_ID` env var with the jelly-hub canister id in development mode. So in the start.sh script that variable was added.
For more information on this, refer to the jelly-js pull request with [this feature](https://github.com/Psychedelic/jelly-js/pulls)
REACT_APP_HUB_ID is consoled logged and getCollections is performed correctly:
> chore: 🤖 added jelly-hub canister id as env var

- src/components/nft-list/nft-list.tsx
- src/integrations/kyasshu/index.ts
- src/store/features/nfts/async-thunks/get-all-nfts.ts
- src/store/features/nfts/nfts-slice.ts
Nft listing pagination
- Created new redux state to store the lastIndex value
- Pulled in the lastIndex value from the store and passed into the loadMore function for loading more nfts
- [GH Pages](https://github.com/orgs/Psychedelic/projects/6/views/11)
https://user-images.githubusercontent.com/51888121/188767714-1257265b-0f3c-41b9-95c5-172348846e90.mov
> feat: 🎸 nft listing pagination

- .scripts/generate-mocked-tokens-v2.sh
Currently, the first mock id is 1 but should be 0. The mock generator should insert from zero.
> fix: 🐛 first index of mock gen start at zero

- src/store/features/nfts/async-thunks/get-all-nfts.ts
- src/store/features/nfts/nfts-slice.ts
It should stop hydrating page data after reaching the total.
⚠️ Depends on https://github.com/Psychedelic/nft-marketplace-fe/pull/515 which should go first
https://user-images.githubusercontent.com/236752/189121732-e1ae22b2-8467-4ffb-bd02-9ca333b4ac1b.mp4
> fix: 🐛 pagination stop hydration

- src/store/features/nfts/async-thunks/get-all-nfts.ts
- src/store/features/nfts/nfts-slice.ts
Before was not showing the last data set of last page, as it should trigger next page on last page match to display it.
> fix: 🐛 show last page data on total page count

- src/components/core/accordions/offer-accordion.tsx
- src/components/modals/cancel-offer-modal.tsx
- src/store/features/marketplace/async-thunks/cancel-offer.ts
- src/store/features/marketplace/async-thunks/get-nft-offers.ts
- src/store/features/marketplace/async-thunks/index.ts
- src/store/features/marketplace/async-thunks/make-offer.ts
- src/store/features/marketplace/marketplace-slice.ts
Enable edit offer integration using jelly js
- [issue-504([the-ticket-url-here](https://github.com/Psychedelic/nft-marketplace-fe/issues/504))
https://user-images.githubusercontent.com/40259256/189328685-a2a4992b-6dd8-4bf5-8820-298c051e7308.mov
> feat: 🎸 enable edit offer integration using jelly js

- src/components/core/accordions/offer-accordion.tsx
- src/components/modals/cancel-offer-modal.tsx
- src/store/features/marketplace/async-thunks/cancel-offer.ts
- src/store/features/marketplace/async-thunks/get-nft-offers.ts
- src/store/features/marketplace/async-thunks/index.ts
- src/store/features/marketplace/async-thunks/make-offer.ts
- src/store/features/marketplace/marketplace-slice.ts
Should have an initial implementation of make offer.
- `jelly-js` make_offer creates multiple popups as it does not use plug batch, was reported.
- [issue-504([the-ticket-url-here](https://github.com/Psychedelic/nft-marketplace-fe/issues/504))
https://user-images.githubusercontent.com/40259256/189271670-f4aefec3-f6df-4d89-b555-b302b091f83f.mov
> feat: 🎸 make offer integration using jelly js (initial)

- src/store/features/nfts/async-thunks/get-all-nfts.ts
- src/store/features/nfts/nfts-slice.ts
The total pages should be deprecated or refactored considering the latest pagination changes in the service side.
https://user-images.githubusercontent.com/236752/189688170-96c4f3d3-1382-442c-8cf0-68db1118dae3.mp4
> fix: 🐛 use last index as cursor not total pages

- src/components/nft-list/nft-list.tsx
- src/store/features/nfts/async-thunks/get-all-nfts.ts
Deprecate page, use instead the fieldname last index.
⚠️ Depends on https://github.com/Psychedelic/nft-marketplace-fe/pull/525
> refactor: 💡 replace page fieldname by last index

- src/components/nft-details/nft-details.tsx
Traits causing the details page to break, see screenshot.
> fix: 🐛 traits missing field causes nft details to break

- src/components/core/accordions/offer-accordion.tsx
- src/components/modals/accept-offer-modal.tsx
- src/components/tables/nft-offers-table.tsx
- src/declarations/marketplace-v2.d.ts
- src/store/features/marketplace/async-thunks/accept-offer.ts
- src/store/features/marketplace/async-thunks/get-nft-offers.ts
- src/utils/parser.ts
Show NFT offers using `jelly js`
- [Issue 536](https://github.com/Psychedelic/nft-marketplace-fe/issues/536)
https://user-images.githubusercontent.com/40259256/189945019-1aa9de64-09bc-465b-be06-7463cd6983b2.mov
> feat: 🎸 show NFT offers using jelly js

- .gitignore
- .scripts/generate-mocked-tokens-v2.sh
The crowns list output is pulled from remote, but the list does not change, as such would be nice to speed up the process by caching.
> perf: ⚡ cache mock generator listing

- .scripts/generate-mocked-tokens-v2.sh
The mock cache file should consider total supply to prevent false positives
> perf: ⚡️ mock cache should consider total supply

- src/config/env.ts
The mainnet.dfinity.network is causing cors issues, as it was deprecated for ic0.app
> chore: 🤖 deprecate mainnet dfinity network for ic0 app
